### ISSUE TITLE
Configuration path, new installation

### ISSUE THREAD

**Issue by hidabe** [sopinet/BasicSymfony#46]
I have done recent installation, and it crash with message:

Configuration path "fos_user.db_driver" cannot be overwritten. You have to define all options for this path, and any of its sub-paths in one configuration section.

**Comment by hidabe** [comment]
If i remove "- resource: common/imports.php", in config.yml, line 3, it work.
I think that it should have any issue about "glob(**DIR**....", and it maybe that is importing two time same file.

**Comment by EmanueleMinotto** [comment]
I think the problem you're having is: http://symfony.com/doc/current/components/config/definition.html#merging-options
Some configurations don't allow an overwriting, what about a solution like this below?

``` yaml
# common/fos_user.yml
fos_user:
  db_driver: '%fos_user.db_driver%'
```

``` yaml
# config/services.yml
parameters:
  fos_user.db_driver: orm
```

Or into the _config/paramters.yml.dist_ if it could change from environment to environment.

**Advantages:**
- no overwriting nor decoration, it's just parameterized
- still one definition in the _common_ directory, instead of different definitions for dev, prod, test, etc...
